apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180s"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30s"
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  proxy-connect-timeout: "30"
  proxy-read-timeout: "180"
  proxy-send-timeout: "180"
  keep-alive: "300"
